title: Vedant Sharma
logo: "/profile.png?raw=true"
description: >
  Senior Frontend Engineer
  <br><br>
  <a href="mailto:vedant.sharma200@gmail.com">vedant.sharma200@gmail.com</a>
  <br>
  <a href="https://www.linkedin.com/in/vedant-sharma07/">LinkedIn</a>
theme: jekyll-theme-minimal
